/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Actor {
  actorId: Generated<number>;
  dob: string | null;
  gender: string | null;
  image: string | null;
  name: string;
  nationality: string | null;
}

export interface ActorFilm {
  actorId: number;
  filmId: number;
}

export interface Film {
  dateAdded: Generated<string>;
  filmId: Generated<number>;
  path: string;
  releaseDate: string | null;
  studioId: number | null;
  title: string;
  metadata: string | null
}

export interface FilmTag {
  filmId: number;
  tag: string;
}

export interface Studio {
  name: string;
  studioId: Generated<number>;
  website: string | null;
}

export interface DB {
  actor: Actor;
  actorFilm: ActorFilm;
  film: Film;
  filmTag: FilmTag;
  studio: Studio;
}
